### ISSUE TITLE
Unable to create database table

### ISSUE THREAD

**Issue by NightFuryPrime** [BlackHacker511/BlackNET#1]
Hello There,

I managed to install everything right like seen in this picture: https://i.imgur.com/GtLxMFF.png
When i open index.php it automatically forwards me to go to install page again.

When i check database, no data was added there.

Any ideas how to fix?

**Comment by BlackHacker511** [comment]
Hey,
I have some questions so I can help you better

1. What is the hosting are you using?
2. Did you update classes/Database.php with you information

**Comment by NightFuryPrime** [comment]
Hello There,

I am using www.endora.cz hosting site.
Yes Database contains everything that it needs [database name, password and
connection

Thank you for your cooperation,

Regards Filip

so 16. 5. 2020 o 18:40 Black.Hacker <notifications@github.com> napísal(a):

**Comment by BlackHacker511** [comment]
So I fixed it the issue was your hosting does not have InnoDB for free users

Solution
1. Open file manager
2. Go to classes/Update.php and edit it
3. in the function "create_table" look for ENGINE=InnoDB  then just delete it and save the file

and it should work

**Comment by NightFuryPrime** [comment]
Solution worked perfectly
