### ISSUE TITLE
Which file

### ISSUE THREAD

**Issue by arsium** [BlackHacker511/BlackNET#1]
I 've done all what you said but in the build what do i have to put ?

**Comment by BlackHacker511** [comment]
AFTER YOU INSTALL THE PHP PANEL
USE THE PANEL URL LIKE THIS
http://yourhost.com/blacknet << in the builder
and it should work

**Comment by BlackHacker511** [comment]
Did u do every thing correct
create database change the config data change file permission going to db.php

**Comment by arsium** [comment]
Yes because i have that : https://ibb.co/JBnQ3q1

**Comment by BlackHacker511** [comment]
So your url is xxxx/777/BOT did use it like that

**Comment by arsium** [comment]
yes i put the ip and then so : xxx.xxx.xxx.xxx:7777/BOT

**Comment by arsium** [comment]
And i dont understand why it doesn't work

**Comment by arsium** [comment]
and now i've tested with noip at http://orcusmyfvrt.ddns.net/BOT/ and always no working

**Comment by BlackHacker511** [comment]
please follow this video for installtion
[https://youtu.be/GyPdu20rC1A](url)

**Comment by arsium** [comment]
Thx man !!! Will you update your panel with new plugins ?

**Comment by BlackHacker511** [comment]
> Thx man !!! Will you update your panel with new plugins ?

yep when i have the time i will rewrite the whole software in a nice framework may be i will add some nice settings and stats
