### ISSUE TITLE
اقتراحات \ تطوير

### ISSUE THREAD

**Issue by NYAN-x-CAT** [BlackHacker511/BlackNET#10]
بارك الله فيك مشروع جميل وقابل للتطوير بشكل أكبر ولكن ينقصه بعض الأمور سأحاول أن أسلط الضوء على بعضها

1- تعديل اسم الكلاسات لتكون سهلة القراءة
مثلا الكلاس الخاص بإنتشار الفلاش ميموري إسمه
Class3.vb
يفضل تغييره. وهكذا

2- وضع الكلاسات المتشابه تحت مجلد واحد
مثلاً https://prnt.sc/pxw6v2

3- مسح كلاس JunkCode.vb
وجوده غير منطقي ولو كان القصد اضافة بعض التمويهات فإذاً يجب عمل مشروع أو كلاس خاص بهمثل هذة الأمور ويتم حقنه من خلال كودوم أو أي مكتبة أخرى.

4- في خاصية تصوير الشاشة ، يفضل حفظ الصورة في الذاكرة بدلاً من حفظها في القرص

5- خاصية سحب الباسوردات يجب ان تكون كبلوقن ينفذ في الذاكرة. يمكنك القاء نظرة على بلوقن المستخدم في مشروع أيسنك-رات.

6- الاستغناء عن الكلاسات و الدوال المقتبسة من انجيرات لأنها تسبب مشكلة في تخطي بعض الحمايات

7- تحسين اسماء المتغيرات
مثلاً H
مفترض أن تكون Host
وهكذا..

هذا ملخص خلال قرائي للسورس لمدة 5 دقائق. لو تلاحظ ستجد أني لم اتطرق للدوال أبداً لأني أحببت أن أسلط الضوء على النقاط الجوهرية الأساسية فقط بعيداً عن محتوى السورس كود. اتمنى أني وفقت في الطرح ويمكنك اغلاق هذة التذكرة الآن.

تحياتي
نيان

**Comment by BlackHacker511** [comment]
حياك اخ نيان ملاحظات جيدة راح تؤخذ في عين الاعتبار
ملاحظة خاصية سحب الباسوردات عبارة عن بقلن دي ال ال ينفذ فالذاكرة
