### ISSUE TITLE
Send commande not working

### ISSUE THREAD

**Issue by sawaq909** [BlackHacker511/BlackNET#12]
Hello,
The send command is not working, it says command sent for keylogger but I cant retrieve any logs from it, the open webpage dont open anything on the computer too, but it says command sent, please fix this issue.

**Comment by BlackHacker511** [comment]
I will look into it

**Comment by BlackHacker511** [comment]
both the keylogger and open webpage functions are working without no issues

try to give the uploads folder 777 permissions 
actually you should give the uploads folder and any folder inside it a 777 permission

this is how to output of the retrive keylogger function should look like
![9e75ea9f68bfe1b2b08611b018c0852a 1](https://user-images.githubusercontent.com/19780715/69493035-e5c7bd80-0eba-11ea-86eb-2e2cff5cf6cc.png)

and this is 40 seconds gif proofs that the open webpage works
https://3.top4top.net/p_14230okq41.gif

Enjoy
