### ISSUE TITLE
Retrieve logs not working

### ISSUE THREAD

**Issue by sawaq909** [BlackHacker511/BlackNET#13]
Thanks for your response, I enabled the 777 permissions but still the retrieve logs option is not working even when I start the keylogger. Also, when I execute the password stealer, I get a .txt file that is encrypted, do you know how to decrypt it?

**Comment by BlackHacker511** [comment]
and I really do not know what is wrong with the keylogger cause it's working without any issues
try to give time after sending the "Start Keylogger" command maybe an hour or so.

The encrypted passwords just user any base64_decoder.
