### ISSUE TITLE
No commands work at all

### ISSUE THREAD

**Issue by pablopeter** [BlackHacker511/BlackNET#14]
Hi Blackhacker,

Thank you for the build and contribution / release.

I have got everything running without issue. However no commands work at all. 

For example i have tried:

- installed software
- screenshot
- ddos
- retrieve key logger

I have checked apache error logs.

I have checked access logs and the only return I can see is the online register notification every now and then for each machine.

I have set correct permissions 777 and checked ownership in the /upload folder. I have also tried to 777 reclusive after the user directory is auto created.

Not sure what else it could be? Are there any apache libraries or settings that this is dependent on maybe?

**Comment by pablopeter** [comment]
I am also guessing it normally writes files ( text files and screenshot images to /uploads/$victim_id

**Comment by BlackHacker511** [comment]
DDOS you need to upgrade to v1.0.1 if you are using v1.0

installed software (Works)
screenshot (Works) you need to wait for 10 seconds
ddos (Works)
retrieve key logger (Works)

Upgrade to v1.0.1

**Comment by pablopeter** [comment]
Hi @BlackHacker511 ,

Thank you for taking the time to reply.

I have already got 1.0.1 ( i downloaded it last night from scratch).

Can you think of any reason as to why its not working?

**Comment by BlackHacker511** [comment]
are you running the botnet on a shared hosting or localhost

**Comment by pablopeter** [comment]
I am running it on a VPS with root access running centos 7, apache, mysql, phpmyadmin.

Fresh install of everything. but no limitations, virus protection or anything similar.

I am wondering if its actually a apache config / addon I require possibly for upload to work correct maybe?

**Comment by BlackHacker511** [comment]
no there is nothing extra to install I build it using XAMPP default libs and settings

the only thing the comes to my mind is php.ini you need to enable file uploading
```
file_uploads = On
```

**Comment by pablopeter** [comment]
So i started fresh.

Installed GUI on centos and installed XAMPP.

Same result.

Netstat on the victim machine (windows 7) shows the initial connection to the server (which creates the folder of pc name in upload folder).

I notice about 30 seconds afterwards it drops off netstat on victim pc completely. it is still running as a process.

if i send a command to it. i never see it arrive on the victim machine.

Something definitively not right.

I also temp tried disabling firewalls on victim machine and blacknet machine.

i have no idea. i have been at this for 15 hours now.

**Comment by pablopeter** [comment]
OK i just found a bug. It does not support FQDN. It only works with IP address for the host.

e.g.

http://subdomain.domain.com/blacknet   DOES NOT WORK
http://00.00.00.00/blacknet DOES WORK

not sure if that is a bug or if you want to make that in notes. It would make a good feature to enable FQDN

**Comment by BlackHacker511** [comment]
oh yeah it's a bug I will fix it
I think the loop in the anti-virus class kill the client

**Comment by pablopeter** [comment]
fyi webroot is now triggering on client

**Comment by BlackHacker511** [comment]
it should work now I fixed the bug v1.0.2

**Comment by BlackHacker511** [comment]
I hope this version works without no issue

**Comment by pablopeter** [comment]
when everything is selected in the builder. im getting a crash of the svhost program on windows 7 pro. have not tested other operating systems. not a massive drama. just thought you should be aware.

Also just about all anti-virus are now triggered including IE, Chrome etc without anti-virus.

**Comment by BlackHacker511** [comment]
hard install is svchost.exe  u could rename to fix the crash
