### ISSUE TITLE
ddos not working 

### ISSUE THREAD

**Issue by gnout113** [BlackHacker511/BlackNET#15]
ddos features not working on the newest version. pls have a check

**Comment by BlackHacker511** [comment]
I will look into it

**Comment by BlackHacker511** [comment]
DDoS is working without no issues on v1.0.3.1

i created some message box to debug code and the ddos is working
https://i.gyazo.com/eefc08dfec46d08516173cf63112ab22.png

in this image i have like 1000 msg box 
https://i.gyazo.com/eefc08dfec46d08516173cf63112ab22.png
