### ISSUE TITLE
really need your help

### ISSUE THREAD

**Issue by gnout113** [BlackHacker511/BlackNET#16]
i really need your support on the ddos features. I have tried to ddos my own website on xampp but nothing thing happen. I checked the Ethernet Graph on Task Manerger , the web server didn't recieve any package from the ddos attack and the website still working well. I using windows 10 as web server and botnet server, using windows 7 as zombie, firewall and antivirus on both machines was off.
Your project is amazing and i hope you wil help me with my problem. Thank you.

**Comment by BlackHacker511** [comment]
What version are you using?
What Builder Features did you select?
Cause I don't know what's your issue?

I just crashed my localhost with Slowloris attack using the botnet

this is proof that the DDoS works

[GIF proofing how DDoS work](https://m.top4top.net/p_1435zyabg1.gif)

![packet is sending for each ddos type](https://2.top4top.net/p_1435stjou1.png)

**Comment by gnout113** [comment]
Thank you so much for helping me. I finally figure it out, Xampp is the reason why i can't use ddos features. Didn't expect that at all.
