### ISSUE TITLE
Access Denied while Retriving Saved Password

### ISSUE THREAD

**Issue by Technowlogy-Pushpender** [BlackHacker511/BlackNET#18]
Hello @BlackHacker511 

Nice Work,

The **PasswordStealer** which you used in the program **requires admin privileges**,
As the **payload doesn't ask for UAC**, payload fails to retrieve password,

 **Multiple Access Denied Popups** is shown in the Victim Machine which is very suspicious

Also Can you please add a **build-in binder**  feature in it

Other than that, all is fine.

Also one request, If possible could you please write a Python based agent , so that I can help you to improve this project.

I made Creds_Harvester [**Which Doesn't need Admin Privileges**] Which is mainly coded for My Advanced [Keylogger](https://github.com/Technowlogy-Pushpender/technowlogger) written in python

**Comment by BlackHacker511** [comment]
It's an issue in Nirsoft Tools next version I will remove the use of Nirsoft Tools 
I found a better chrome retriever firefox is a little bit hard to decrypt and retrieve

Build-in binder it's a nice idea I will try to add it

and there is a Python Payload in v1.0.0 if you could go to release page download v1.0 there is a simple Python-based payload and builder
