### ISSUE TITLE
What does "Dropbox Spread" do

### ISSUE THREAD

**Issue by iii235** [BlackHacker511/BlackNET#2]
I built a client and selected the option, but the builder didn't prompt me about Dropbox or anything. Also, how does the Binder option work?

**Comment by BlackHacker511** [comment]
Dropbox Spread
if the client has dropbox installed it will move your client to that dropbox folder

Binder, it binds an executable file to your output, like if you want to bind an XMR Miner or any other malicious tools.

**Comment by iii235** [comment]
Oh, and where do you find the keylogger logs?

**Comment by BlackHacker511** [comment]
After you start the keylogger

Wait for it to collect data after that you can run retrieve logs and you will logs in the client folder you can click on the client name to see what in the folder but make sure that upload folder has 777 permissions recursively

**Comment by iii235** [comment]
What is the path to the logs file?

**Comment by BlackHacker511** [comment]
@iii235 in the Temp folder

**Comment by iii235** [comment]
Is it the temp folder outside of the Blacknet folder on your hosting website?

**Comment by BlackHacker511** [comment]
@iii235 No no

Windows Temp folder %temp%
