### ISSUE TITLE
PasswordPlugin

### ISSUE THREAD

**Issue by arsium** [BlackHacker511/BlackNET#21]
EDIT : CORRECTED

Also did you write it alone ?

**Comment by BlackHacker511** [comment]
No i modified the original code by underc0de
did it work ?

**Comment by arsium** [comment]
Yes it did work i just add some things to make it better and working as library

**Comment by arsium** [comment]
Also from which site does the original come from  ?

**Comment by BlackHacker511** [comment]
https://underc0de.org
a spanish hacking forum it's an old code but still work on the new chrome

**Comment by arsium** [comment]
I tested that :)
