### ISSUE TITLE
Mutliple Issues In Latest Botnet

### ISSUE THREAD

**Issue by Technowlogy-Pushpender** [BlackHacker511/BlackNET#22]
* Issue 1 :
When We Closed the Binder after clicking on **Save Settings**, It Also Closes the **Generator** with the **Binder Setting** Dialog box.

* Issue 2 :
Icon is Not Changed to the Selected Icon. [**File extension: .ico**]

* Issue 3 :
Also the **Binder** Didn't Work for Me, I get a **Compiled Successfully Message** But, when i run the payload, it doesn't run the Legitimate file

* Issue 4:
Following Commands I tested, All gives the message that **Command Executed Successfully** but didn't get any result.

* Issue 5:
When I click on Uninstall Client, it didn't removed the Client from the Panel

The Ticked One Works Fine,
- [ ] Ping 
- [X] Upload File 
- [x] Show MessageBox
- [x] Take Screenshot
- [ ] Installed Software
- [ ] Execute Script
- [ ] Elevate User Status
- [ ] Start Keylogger 
- [ ] Retrives Logs

Also Both **Stealer** and **Webpage Open** menus commands didn't works for me

**Improvement :**

(1) Please Add a Button In "viewupload.php" Which will give the functionality
    to Delete the Files.

(2) You use Windows Registry to make file persistence, but you specified the path,
of the current executed file, suggested to replicate the Botnet in Appdata/Temp and then 
add it to path of registry

### All commands in 000webhost says only Result "Command Completed successfully", but no result is get from the botnet

**Comment by BlackHacker511** [comment]
Thank you for detailing your issue I will look into it
1. Issue 1: confirmed
2. Issue 2: invalid
3. Issue 3: confirmed
issue 4, issue 5 related to the binder.
binder does not client won't work.

**Comment by BlackHacker511** [comment]
I pushed a new hotfix a compiled version is fixed the source code fixed it was a binder issue
