### ISSUE TITLE
Take Screenshot problem

### ISSUE THREAD

**Issue by LukasCCB** [BlackHacker511/BlackNET#28]
**Error #1**

Select user
Command: Take Screenshot

Empty uploader screenshot, not work.

HacKed_3C4E0000 | 207.x.x.x | 980108 | User |   | Microsoft Windows 10 Pro | 23-12-2019 | Windows Defender | Online

When i see in Upload folder, are empty. not work. can you tell me what wrong?

Folder inside create with "HacKed_3C4E0000" but, empty file photo.

**Error #2** 

SMTP to Forgot Password are Working
SMTP to code token 2FA not Working

Thanks.

**Comment by BlackHacker511** [comment]
Did you give the upload folder 0777 permissions?

**Comment by LukasCCB** [comment]
When i infect myself and my another computer work normal screenshot uploader.

**Comment by LukasCCB** [comment]
> Did you give the upload folder 0777 permissions?

When i infect myself and my another computer work normal screenshot uploader.

**Comment by BlackHacker511** [comment]
are you using a Webhosting if yes then don't use SMTP disable it's not required the script will use PHP default mail function

**Comment by LukasCCB** [comment]
> are you using a Webhosting if yes then don't use SMTP disable it's not required the script will use PHP default mail function

Using MAMP Pro.
SMTP to Forgot Password work, only for 2FA not. Folder permission are OK! nvm, i'll re-run, i have changed all Template. maybe problem my. thx
