### ISSUE TITLE
Online User BUG and Password Recovery BUG

### ISSUE THREAD

**Issue by NightFuryPrime** [BlackHacker511/BlackNET#3]
Hello,

I found out that user still appears online even the service(process/client) is not running. https://i.imgur.com/XRKUDU8.png

After running password recovery i encountered error: An unexpected error occurred The remote server returned an error: (404) Not Found.

https://i.imgur.com/Fczl201.png

**Comment by BlackHacker511** [comment]
Hey,

Yes you need to enable a cronjob with the file jobs/ping.php

And could you please make sure that PasswordStealer.dll is in the plugins folder

**Comment by NightFuryPrime** [comment]
I can setup cron job for ping and remove each 30min by the system - can you make feature that executes this cron jobs from main window? Add there feature where you can manually click and execute cron job from main window.

**Comment by NightFuryPrime** [comment]
yup, uploaded the .dll for password recovery and worked fine... maybe if you can include this hints in installation manual, would be great
