### ISSUE TITLE
Cant Connect

### ISSUE THREAD

**Issue by Dontmindmes** [BlackHacker511/BlackNET#3]
I tried connecting using the exe and it dosent connect so i tried addtarget.php
and got this

`
Fatal error: Uncaught Error: Call to undefined function mysql_escape_string() in C:\xampp\htdocs\BlackNET\connection.php:88 Stack trace: #0 C:\xampp\htdocs\BlackNET\connection.php(5): CheckData('test') #1 {main} thrown in C:\xampp\htdocs\BlackNET\connection.php on line `88``

**Comment by BlackHacker511** [comment]
It seems there is a function that xampp do not have i will look in to it.

**Comment by BlackHacker511** [comment]
So the fix is
Edit connection.php
Find a function called  "CheckData"
Remove "$data=mysql_escape_string($data) ;" 
Save.
