### ISSUE TITLE
Struggling with the commands

### ISSUE THREAD

**Issue by LelouchIsBae** [BlackHacker511/BlackNET#30]
The only command that seems to be working is the pop up message. Every other one is failing to work. I am guessing it is because I haven't set permissions to 777 like other threads say but I don't know how to do that. I am bad at this sort of things so If anyone could enlighten me on how to do so I will be very grateful.

If my other issue gets responded to and the other commands (such as open browser, password stealer) start working. Where would it show up in? What folder?

**Comment by BlackHacker511** [comment]
What is the hosting your using ?
So i could better understand your issue.

**Comment by BlackHacker511** [comment]
and all your clients' files are under upload/"Client ID"

**Comment by LelouchIsBae** [comment]
I am using 000webhosting

**Comment by BlackHacker511** [comment]
watch this view I just uploaded it
the video will teach how to install the panel step by step in English
https://youtu.be/ReKOuh6fFcQ
