### ISSUE TITLE
Cant log in nor can I change passwords

### ISSUE THREAD

**Issue by LelouchIsBae** [BlackHacker511/BlackNET#33]
![error](https://user-images.githubusercontent.com/51431749/71629058-4092ba00-2bc9-11ea-9de3-bffbc52f0b67.png)
So it won't let me log in even though I have the correct log in credentials, and when I try to change passwords it won't even take my email. It just says wrong Username.
Anyway to fix?

**Comment by BlackHacker511** [comment]
1. What type of hosting are you using?
2. Did you run install.php?
3. Did you change your credentials before?
4. Did you add a valid email address to your account?
5. Did you change anything in Database.php beside your DB information?
6. Did you change anything in the admin table like the password without hashing it?

**Comment by LelouchIsBae** [comment]
1) 000webhost
2)yes, things worked before like i could infect people and use the commands. It's almost like it's locking me out. It worked before but now It won't let me back in my own account 
3) They have been the same and have never changed
4) Isn't the email the same one that is attached to the website?
5) No I only changed the 3 things the view showed us. Username, Password and the other thing
6)What admin table are you referring to?

**Comment by BlackHacker511** [comment]
2)yes, things worked before like i could infect people and use the commands. It's almost like it's locking me out. It worked before but now It won't let me back in my own account

What did you now before the problem, did install the script again

They have been the same and have never changed
admin:admin

Isn't the email the same one that is attached to the website?

in your user settings page, there is an email input you need to add a valid email so the system could  send and reset password link

**Comment by LelouchIsBae** [comment]
Oh it works now. Thanks!
