### ISSUE TITLE
How to work with Password Stlear??

### ISSUE THREAD

**Issue by technicaldada** [BlackHacker511/BlackNET#35]
It just says command have been send.. Same case happens in keyloggers option.. where is the outputs??

**Comment by BlackHacker511** [comment]
The Output will be in the uploads folder
just give the uploads folder 0777 permissions <= IMPORTANT STEP

same as keylogger, screenshot, cookies, and programmlist

Click on the client name and you will find the stolen data

**Comment by technicaldada** [comment]
everything is right in 000webhost...but not working...

Check the screenshots of upload folder
![Screenshot_2020-01-10_08-19-26](https://user-images.githubusercontent.com/32122182/72121877-526f1c80-3382-11ea-9bc9-a9d8cea6ee72.png)

Check the permissions
https://imgur.com/1LEsFs6.png

**Comment by BlackHacker511** [comment]
I will look into it

**Comment by BlackHacker511** [comment]
Works great on my end
Make sure the client is online
Make sure there is at least one saved password in Chrome
Make sure then client AV is disabled or does not detect your Trojan
Make sure that the permissions are recursive each and every folder inside uploads is 777
