### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by 0x00chad** [BlackHacker511/BlackNET#41]
The Client show online even if the computer is turned of for an hour.,and if i use watchdog the cpu usage turn to 100% im using windown 10 1909.

**Comment by BlackHacker511** [comment]
As for the first issue that's why i created ping.php and i will look in to second issue

**Comment by 0x00chad** [comment]
how many minutes before the client execute the command in the server? or reconnect to the server because in me the client only execute the command in the server only if I open the client. and if i restart the client thats the time he execute my next command. sorry for my english not my language.

**Comment by BlackHacker511** [comment]
yes, the client needs to be connected to execute a command it takes seconds not minutes maybe 10 or 20 seconds depends on the client's internet connection and the server command loop.

**Comment by ominitric** [comment]
the stub execute the command on the server only few minutes after I open the stub, only execute the command on the server only if I open the stub and fails to send back again after some minutes. and till i restart the pc before it could execute my next command. This is a good project but why is this happening.?

**Comment by ominitric** [comment]
I’ll love if you could get it that issue fixed, this is a great project thumbs up man❤️👍

**Comment by BlackHacker511** [comment]
> the stub execute the command on the server only few minutes after I open the stub, only execute the command on the server only if I open the stub and fails to send back again after some minutes. and till i restart the pc before it could execute my next command. This is a good project but why is this happening.?

Could you open a new issue with more information
