### ISSUE TITLE
Clients not showing up in web gui.

### ISSUE THREAD

**Issue by xer0sec** [BlackHacker511/BlackNET#42]
**Describe the bug**

Clients are not showing up in the web gui in the latest (2.5) they are showing in the phpmyadmin (ex:idlkfajlfja_blackbot) everything seems to install just fine. 1.x  still works fine, but without the added features of course. 2.0 and above seem to give me the same problem though

also, completed commands show in log. (ex: privileges escalated successfully)   

Im using Debian with firefox 68.2.0esr (64-bit) 

Let me know if there is anything else you like to know, or screenshots...logs. i would have included them but not sure what's relevant or not to be honest  

Thanks, and really nice work by the way. The best out there in my opinion.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlackHacker511** [comment]
1. are there any clients?
2. did you execute any commands that led to the client disappearing?
3. please add some screenshots of the PHPMyAdmin clients and command tables and web panel?
4. are there any features you chose in the builder?

**Comment by FalloutHCF** [comment]
can confirm happening for me too, i have no errors and the client builder says my panel is enabled. when i run the compiled exe my panel displays 0 users

**Comment by BlackHacker511** [comment]
I just tested it there are no errors and the client showed up normally

![____](https://user-images.githubusercontent.com/19780715/72687412-94c8f400-3b0e-11ea-995e-66d64b942ce6.png)

**Comment by BlackHacker511** [comment]
> can confirm happening for me too, i have no errors and the client builder says my panel is enabled. when i run the compiled exe my panel displays 0 users
> EDIT:
> https://youtu.be/r7OF5y9MdRk video showing that i have no erros yet still doesnt show me connected

I just tested it there are no errors and the client showed up normally

![____](https://user-images.githubusercontent.com/19780715/72687412-94c8f400-3b0e-11ea-995e-66d64b942ce6.png)

**Comment by FalloutHCF** [comment]
> 
> 
> > can confirm happening for me too, i have no errors and the client builder says my panel is enabled. when i run the compiled exe my panel displays 0 users
> > EDIT:
> > https://youtu.be/r7OF5y9MdRk video showing that i have no erros yet still doesnt show me connected
> 
> I just tested it there are no errors and the client showed up normally
> 
> ![____](https://user-images.githubusercontent.com/19780715/72687412-94c8f400-3b0e-11ea-995e-66d64b942ce6.png)

i followed this tutorial " https://www.youtube.com/watch?v=ReKOuh6fFcQ " does this still work for v2.5?

**Comment by BlackHacker511** [comment]
> > > can confirm happening for me too, i have no errors and the client builder says my panel is enabled. when i run the compiled exe my panel displays 0 users
> > > EDIT:
> > > https://youtu.be/r7OF5y9MdRk video showing that i have no erros yet still doesnt show me connected
> > 
> > 
> > I just tested it there are no errors and the client showed up normally
> > ![____](https://user-images.githubusercontent.com/19780715/72687412-94c8f400-3b0e-11ea-995e-66d64b942ce6.png)
> 
> i followed this tutorial " https://www.youtube.com/watch?v=ReKOuh6fFcQ " does this still work for v2.5?

yes it's the same idea
but if you updating from an older version then you need to run update.php

**Comment by FalloutHCF** [comment]
> 
> 
> > > > can confirm happening for me too, i have no errors and the client builder says my panel is enabled. when i run the compiled exe my panel displays 0 users
> > > > EDIT:
> > > > https://youtu.be/r7OF5y9MdRk video showing that i have no erros yet still doesnt show me connected
> > > 
> > > 
> > > I just tested it there are no errors and the client showed up normally
> > > ![____](https://user-images.githubusercontent.com/19780715/72687412-94c8f400-3b0e-11ea-995e-66d64b942ce6.png)
> > 
> > 
> > i followed this tutorial " https://www.youtube.com/watch?v=ReKOuh6fFcQ " does this still work for v2.5?
> 
> yes it's the same idea
> but if you updating from an older version then you need to run update.php

i started with v2.5 so i didnt need to update but do you know any possible reasons this could be happening?

**Comment by BlackHacker511** [comment]
> > > > > can confirm happening for me too, i have no errors and the client builder says my panel is enabled. when i run the compiled exe my panel displays 0 users
> > > > > EDIT:
> > > > > https://youtu.be/r7OF5y9MdRk video showing that i have no erros yet still doesnt show me connected
> > > > 
> > > > 
> > > > I just tested it there are no errors and the client showed up normally
> > > > ![____](https://user-images.githubusercontent.com/19780715/72687412-94c8f400-3b0e-11ea-995e-66d64b942ce6.png)
> > > 
> > > 
> > > i followed this tutorial " https://www.youtube.com/watch?v=ReKOuh6fFcQ " does this still work for v2.5?
> > 
> > 
> > yes it's the same idea
> > but if you updating from an older version then you need to run update.php
> 
> i started with v2.5 so i didnt need to update but do you know any possible reasons this could be happening?

I really don't know I need more information


Are you using a hosting or on a local server?

If yes what's the hosting?

Is there anything in the database?

Did you choose any specific features in the builder?

Is your anti-virus running?

Is there any firewall that blocks the HTTP Connection?

I need screenshots from the database specifically clients and commands table

**Comment by FalloutHCF** [comment]
Are you using a hosting or on a local server? : hosting

If yes what's the hosting? : 000webhost

Is there anything in the database? : if you mean tables etc then yes

Did you choose any specific features in the builder? : no, i followed the tutorial exactly

Is your anti-virus running? : No

Is there any firewall that blocks the HTTP Connection? : No

I need screenshots from the database specifically clients and commands table : attached below
![clients](https://user-images.githubusercontent.com/25876660/72688720-404e5600-3ac7-11ea-9062-abba445b01cd.PNG)
![commands](https://user-images.githubusercontent.com/25876660/72688723-417f8300-3ac7-11ea-93e4-843810db34ec.png)

**Comment by BlackHacker511** [comment]
> Are you using a hosting or on a local server? : hosting
> 
> If yes what's the hosting? : 000webhost
> 
> Is there anything in the database? : if you mean tables etc then yes
> 
> Did you choose any specific features in the builder? : no, i followed the tutorial exactly
> 
> Is your anti-virus running? : No
> 
> Is there any firewall that blocks the HTTP Connection? : No
> 
> I need screenshots from the database specifically clients and commands table: attached below
> ![clients](https://user-images.githubusercontent.com/25876660/72688720-404e5600-3ac7-11ea-9062-abba445b01cd.PNG)
> ![commands](https://user-images.githubusercontent.com/25876660/72688723-417f8300-3ac7-11ea-93e4-843810db34ec.png)

good so there is a client in the commands table but not in the clients table

I will see what's the problem then I will push an update if there is one.

**Comment by BlackHacker511** [comment]
> Are you using a hosting or on a local server? : hosting
> 
> If yes what's the hosting? : 000webhost
> 
> Is there anything in the database? : if you mean tables etc then yes
> 
> Did you choose any specific features in the builder? : no, i followed the tutorial exactly
> 
> Is your anti-virus running? : No
> 
> Is there any firewall that blocks the HTTP Connection? : No
> 
> I need screenshots from the database specifically clients and commands table : attached below
> ![clients](https://user-images.githubusercontent.com/25876660/72688720-404e5600-3ac7-11ea-9062-abba445b01cd.PNG)
> ![commands](https://user-images.githubusercontent.com/25876660/72688723-417f8300-3ac7-11ea-93e4-843810db34ec.png)

what is your 000webhost current PHP version?

**Comment by BlackHacker511** [comment]
yes there is an issue with 000webhost i just found it
on localhost everything works but not on 000webhost

i will try to fix it

**Comment by FalloutHCF** [comment]
> 
> 
> yes there is an issue with 000webhost i just found it
> on localhost everything works but not on 000webhost
> 
> i will try to fix it

thanks so much

**Comment by BlackHacker511** [comment]
Bug fixed and I pushed a hotfix just update you files.

**Comment by BlackHacker511** [comment]
> 
> 
> > yes there is an issue with 000webhost i just found it
> > on localhost everything works but not on 000webhost
> > i will try to fix it
> 
> thanks so much EDIT : my php version is 7.2

Bug fixed and I pushed a hotfix just update you files.
