### ISSUE TITLE
000webhost closed account

### ISSUE THREAD

**Issue by karilvo** [BlackHacker511/BlackNET#5]
Hey,

Do you know of any web hosts that allow us to use your work on their site? I tried webhost a while back and they closed account after day.

**Comment by BlackHacker511** [comment]
I recommend a good VPS Atlantic.net has a 12 months free server just set it up and install the panel on it I use it for my black hat activities and it served me well ❤️

**Comment by karilvo** [comment]
Ok, tyvm !
