### ISSUE TITLE
2FA issues

### ISSUE THREAD

**Issue by s1l3n7h0s7** [BlackHacker511/BlackNET#52]
Hey so i haven't had many issues, tasks don't always come back other wise delayed but can be worked around. Though suddenly the 2FA stopped working and kept returning "HTTP error 500", this issue seems to continue even after doing the v3 update

**Comment by BlackHacker511** [comment]
I will look into this 2f issue

**Comment by BlackHacker511** [comment]
Could you please describe the issue because 2FA is workin' on my end perfectly

**Comment by s1l3n7h0s7** [comment]
Its definetaly not affecting everyone if anyone else. But when trying to
activate the 2FA it tries to load the authsettings.php page and returns a
500 error. Have tried everything from reinstalling BNet to an entire server
reconfig. Ill get it sorted eventually and relay the issue incase anyone
else experiences but was checking if youd come across it before


On Feb 7, 2020 at 11:18, Black.Hacker <notifications@github.com> wrote:

Could you please describe the issue because 2FA is workin' on my end
perfectly

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BlackHacker511/BlackNET/issues/52?email_source=notifications&email_token=AKSP2S5UPEK5CFAANIWDYHLRBURPHA5CNFSM4KRER5Q2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELCH6FI#issuecomment-583302933>,
or unsubscribe
