### ISSUE TITLE
Commands not being executed.

### ISSUE THREAD

**Issue by Ejwhite25** [BlackHacker511/BlackNET#54]
Attempting to run the bot on a virtual machine (Windows 7). It runs and reports back to the server, but upon attempting to run commands (screenshot, shutdown, etc.) The commands aren't being executed 
I have tried unchecking different features, but even without features, it is still not working.

**Comment by panpansh** [comment]
did you have access to upload folder from victim ip ?

**Comment by BlackHacker511** [comment]
Watch this video
https://youtu.be/eIOd8Xo7CvY

**Comment by Ejwhite25** [comment]
Done all that and still nothing, the upload folder is set to 0777 for permissions. I found a PHP error log file and these 2 errors I've gotten consistently":
PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in /home/ejwhite25/public_html/classes/Clients.php on line 258

PHP Warning:  mkdir(): File exists in /home/ejwhite25/public_html/connection.php on line 43

**Comment by BlackHacker511** [comment]
How did you get these errors?
What page did you execute?
Provide screenshot from the clients and commands table

```
PHP Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in /home/ejwhite25/public_html/classes/Clients.php on line 258
```

**Comment by Ejwhite25** [comment]
<img width="1440" alt="Screen Shot 2020-02-08 at 2 10 56 AM" src="https://user-images.githubusercontent.com/49687191/74082610-019e2280-4a19-11ea-8c94-13ed46e38b72.png">
<img width="1143" alt="Screen Shot 2020-02-08 at 2 14 18 AM" src="https://user-images.githubusercontent.com/49687191/74082626-0f53a800-4a19-11ea-8fd7-a8641ec6dea2.png">
<img width="1141" alt="Screen Shot 2020-02-08 at 2 11 19 AM" src="https://user-images.githubusercontent.com/49687191/74082636-25616880-4a19-11ea-90da-78694733eef4.png">

**Comment by BlackHacker511** [comment]
Did you update to v3.0.0.0.1 ?

i need screenshots from the database aka phpmyadmin
if you don't how to login to phpmyadmin from cPanel locate it 
search for phpmyadmin in cPanel and take screenshots from the clients and commands table

and you need to try update old clients or this release will not work on them because of the connection password .

**Comment by Ejwhite25** [comment]
> Did you update to v3.0.0.0.1 ?
> 
> i need screenshots from the database aka phpmyadmin
> if you don't how to login to phpmyadmin from cPanel locate it
> search for phpmyadmin in cPanel and take screenshots from the clients and commands table
> 
> and you need to try update old clients or this release will not work on them because of the connection password .

I have fully updated to v3.0.0.0.1, here are the screenshots:
<img width="1135" alt="Screen Shot 2020-02-08 at 2 27 08 AM" src="https://user-images.githubusercontent.com/49687191/74082796-d0beed00-4a1a-11ea-9f0e-985fe975e5c6.png">
<img width="1135" alt="Screen Shot 2020-02-08 at 2 27 40 AM" src="https://user-images.githubusercontent.com/49687191/74082799-d3b9dd80-4a1a-11ea-9ba1-0c52c001fb08.png">
<img width="1216" alt="Screen Shot 2020-02-08 at 2 28 21 AM" src="https://user-images.githubusercontent.com/49687191/74082800-d4527400-4a1a-11ea-944e-0a93dbabb8f1.png">

**Comment by BlackHacker511** [comment]
Did you try v3.0.0.0.1 on your self and tried some commands to see if it works

**Comment by Ejwhite25** [comment]
> Did you try v3.0.0.0.1 on your self and tried some commands to see if it works

Yes, I have updated to 3.0.0.0.1 and tried commands on both a windows 7 and Windows 10 VM, but got nothing.

**Comment by BlackHacker511** [comment]
@Ejwhite25
It is interesting issue but I will look in to it if i find the issue i will update the panel for now downgrade to v2.5.0.1 until i fix the issue

**Comment by BlackHacker511** [comment]
A new update has been released and I removed connection password
I noticed that after I add this feature to many users reported the same issue.

if you find any issues in the new release please tell me.

Enjoy.
