### ISSUE TITLE
Where can I change the connection password

### ISSUE THREAD

**Issue by agentReef** [BlackHacker511/BlackNET#55]
cann't find the place where to find the connection password, you said that the default is: Au9SmrqefaAr1DYFnZEpgGaZYdepAs5i, where can I change the defualt?

**Comment by BlackHacker511** [comment]
from the network settings page
settings.php

**Comment by agentReef** [comment]
well, in the setting.php I only see the smtp setting and captcha setting, I didn't see any things related to connection, by the way, How can I change the log the client send back? I try to change the information in source code in phpstub, and build it in release mode, then name of svhost to stub and rplace it ,but it does work, seem's like the old one are much more bigger

**Comment by agentReef** [comment]
well, I find out the problem's,  I belive is the language setting, when I type : "every things ok", it return all good, But when I try to type:"seem like just can't use other", the log infor return like this:" seem like just can&amp;#039;t use others. and when I try to tipe japaness or french, It no longger return values.
How can I solve this?

**Comment by BlackHacker511** [comment]
> well, in the setting.php I only see the smtp setting and captcha setting, I didn't see any things related to connection, by the way, How can I change the log the client send back? I try to change the information in source code in phpstub, and build it in release mode, then name of svhost to stub and rplace it ,but it does work, seem's like the old one are much more bigger

that's mean you did not update the panel.

> well, I find out the problem's, I belive is the language setting, when I type : "every things ok", it return all good, But when I try to type:"seem like just can't use other", the log infor return like this:" seem like just can&#39;t use others. and when I try to tipe japaness or french, It no longger return values.
> How can I solve this?

i did not try any other language only Arabic and English but this an interesting issue the database uses UTF-8 char settings so it should support all existing languages.
