### ISSUE TITLE
Passwords Plugin

### ISSUE THREAD

**Issue by arsium** [BlackHacker511/BlackNET#59]
The password plugin doesn't work anymore since last update of chrome.

**Comment by BlackHacker511** [comment]
I will look into it i didn't try it with the last update

**Comment by Pypygay** [comment]
https://github.com/LimerBoy/Adamantium-Thief
Try use it for password and cookies stealer

**Comment by BlackHacker511** [comment]
@Pypygay this look like an interesting project i will see how to implement it using VB.NET
