### ISSUE TITLE
python error 

### ISSUE THREAD

**Issue by WOLFIE-OG** [BlackHacker511/BlackNET#6]
i am using python 3.6.6 i get his error on the stub 
Traceback (most recent call last):
  File BlackNET-master\BN Stub.py, line 11, in <module>
    uid = cid +  '_' + base64.b64encode(os.getlogin());
  File \AppData\Local\Programs\Python\Python36\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
>>>

**Comment by BlackHacker511** [comment]
Thank you for pointing the issue
i uploaded a fixed version for the python stub that works on Python 2 and 3
