### ISSUE TITLE
how can i use the old password stealer for google chrome

### ISSUE THREAD

**Issue by ethanchua07** [BlackHacker511/BlackNET#6]
itry to replace the password stealer from the old version and it doesn't seems to work. like if the client have old chrome. i think the new stealer doesn't work with old chrome.

**Comment by BlackHacker511** [comment]
The stealer should work on old and new Chrome it has that capability built in but if the client does not have any passwords saved on Chrome then nothing will happen the Stealer will find the password sqlite empty the it will just close it self.

**Comment by ethanchua07** [comment]
my bad, i remember i use ccleaner to my pc and cleared all password. sorry.

**Comment by ethanchua07** [comment]
will this the last version like in the title indicate?

**Comment by BlackHacker511** [comment]
@ethanchua07 

this is the last major release there will be miner releases for bug fixes and small features

Enjoy

**Comment by ethanchua07** [comment]
aw., for the last time can u add remote terminal like when u send command u can get the result?

**Comment by BlackHacker511** [comment]
that is not a function in a botnet sorry 

for a remote shell, I need TCP connection not HTTP Request.

HTTP Request with TCP will just lag the code but I might I add something like what VertexNET had

Just sending command and retrieve results in a text file.

**Comment by ethanchua07** [comment]
yes Just like installed software command when execute retrieve the result in a textfile or show the result in logs. that will be usefull.

**Comment by ethanchua07** [comment]
and a function to upload a file to webserver. like when you know where the file exact location you just enter the exact location and upload to server.
