### ISSUE TITLE
Password stealer not functioning

### ISSUE THREAD

**Issue by xdep** [BlackHacker511/BlackNET#61]
When saving passwords in IE and Firefox the stealer does not pick it up nor does it return anything except the common log "Password Stealer has been executed"

Tested this in a fresh Windows 10 Enterprise Virtual.

**Comment by BlackHacker511** [comment]
The Stealer does not work on Firefox or IE just Chrome 
though it does not work the last Chrome but I'm working a new plugin that steal passwords from all browsers.
