### ISSUE TITLE
Client not receiving command anymore after a period of time

### ISSUE THREAD

**Issue by ominitric** [BlackHacker511/BlackNET#62]
Hello black, there is an issue you might not notice here, stub won’t send feedback command anymore after few commands been sent until you click the stub again, it only execute the last command again after I rerun the stub manually, after sending few commands or after a period of time, stub won’t respond anymore and i went to check it still on tasks list in windows running process, but any command been sent won’t be uploaded, even after waiting hours, still the same, tested on two different servers and stubs.

**Comment by ominitric** [comment]
I can send you screenshots and give you access to the server
![image](https://user-images.githubusercontent.com/24626466/75088136-8cb70680-5549-11ea-8d0a-0daa0eec0213.jpg)‘
 The stub is Office-Files.exe
It indicated been online and crone is running
![image](https://user-images.githubusercontent.com/24626466/75088257-f84da380-554a-11ea-8fa4-4fd88edc0e42.jpg)

3 different commands sent non worked 
![image](https://user-images.githubusercontent.com/24626466/75088263-12878180-554b-11ea-8690-ccf5b7be0ed7.jpg)
The cookies.sqlite there was the command which responded last. After that all other commands not working and stub is still running.

**Comment by BlackHacker511** [comment]
I will look in to it
It could be an issue with the command handler
If i find an issue i will upload a new fixed update

**Comment by ominitric** [comment]
Kudos bro, thumbs up, can we chat on icq or telegram, what’s your user id?

**Comment by BlackHacker511** [comment]
It should work now
I tried it on my machine left the connection open for 5 hours then tried again it works
v3.0.0.5
