### ISSUE TITLE
Command Panel Bug

### ISSUE THREAD

**Issue by Vyndar** [BlackHacker511/BlackNET#63]
Used Windows 7 and Windows 8.1 for test purposes.
After executing the built stub it shows up on the web panel as expected but whatever command I attempt to execute it doesn't do anything. Also tried to execute "Uninstall" on both machines and still with no success. Seems like the panel received information but it doesn't send any to the bots.
After killing the process the bot still shows as "online" in the panel.
Using PHP version 7.3

**Comment by Vyndar** [comment]
Forgot to mention that Im testing the latest version 3.0.0

**Comment by BlackHacker511** [comment]
@Vyndar try v3.0.0.0.5

**Comment by Vyndar** [comment]
I tried with v3.0.0.5 as well but same thing happens. Also tried on different host and still the same. Info gets to the panel but doesn't get to the bots like commands, pings etc.

**Comment by NARC951** [comment]
yes i am having the same problem works find on lan network but when i turn over to live on the internet no commands works via the admin panel

**Comment by NARC951** [comment]
all my bots show online but i can send any commands to them. =(

**Comment by Vyndar** [comment]
I just tested and I can confirm that it works fine on the local server but it doesn't on the live one.

**Comment by dzhackmall** [comment]
> I tried with v3.0.0.5 as well but same thing happens. Also tried on different host and still the same. Info gets to the panel but doesn't get to the bots like commands, pings etc.

how to install 3.0.0.5 release?i'm download 3.0.0.5 but install dispaly 3.0.0.1.

**Comment by CardGods** [comment]
> 
> 
> > I tried with v3.0.0.5 as well but same thing happens. Also tried on different host and still the same. Info gets to the panel but doesn't get to the bots like commands, pings etc.
> 
> how to install 3.0.0.5 release?i'm download 3.0.0.5 but install dispaly 3.0.0.1.

Did you fix it? It seems that on any live website when using it, the commands just never send. Another issue I noticed is that bots die REALLY quickly (looked at previous messages, apparently this is a Windows Defender issue).

Could anyone provide an update on how to fix the issue with sending commands? They seem to not do anything.

**Comment by BlackHacker511** [comment]
There are no issues I just forget a requirement 
callAPI function uses curl you need it to get the client country
see the new requirements and enable php_cURL from your cPanel or if you using VPS Server

```bash
apt install php_curl
```
