### ISSUE TITLE
bug with excute file like using script and upload file

### ISSUE THREAD

**Issue by agentReef** [BlackHacker511/BlackNET#64]
When I try to use the "upload file", the stub keep return error, and I believe this is because of some bug on return function.  And also, is it possible to use command line to directlly build the stub instead of open a software to build? I believe command line build function doesn't need to be too complex, all it need to to is just add the address of the website to the stub.

**Comment by BlackHacker511** [comment]
I've found the bug and it will be fixed in the next release.
