### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by s1l3nt78** [BlackHacker511/BlackNET#65]
After selecting options and choosing obfuscator option, instead of putting that file into crypto obfuscator 2013 you can also use deepsea obfuscator 4.4.1.8. The result is pretty good. When downloading the file from my vm to an external machine with macafee pro the file downloaded correctly without being stopped by chrome, the macafee web extention file scanner or my running AV
![Annotation 2020-03-10 001331](https://user-images.githubusercontent.com/44367179/76262257-840e4200-6264-11ea-8faa-7e44c16d6bab.png)

**Comment by xxCleef** [comment]
Nice
