### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by rodrigopereiraaa** [BlackHacker511/BlackNET#69]
I get this error when trying to run install.php.
Any help would be appreciated 

Problem in executing the SQL query CREATE TABLE `admin` ( `id` int(11) UNSIGNED NOT NULL, `username` text NOT NULL, `password` text NOT NULL, `email` text NOT NULL, `role` text NOT NULL, `s2fa` varchar(10) NOT NULL, `secret` varchar(100) NOT NULL, `sqenable` varchar(10) NOT NULL, `question` text NOT NULL, `answer` text NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by BlackHacker511** [comment]
This means that BlackNET is already installed my friend.

check phpmyadmin you will that the whole database is installed
