### ISSUE TITLE
another error 

### ISSUE THREAD

**Issue by WOLFIE-OG** [BlackHacker511/BlackNET#7]
Traceback (most recent call last):
  File "C:\Users\WOLFIE\Music\BN Stub.py", line 12, in <module>
    basecode =base64.urlsafe_b64encode(username.encode('UTF-8')).decode('ascii')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by BlackHacker511** [comment]
I look into it

**Comment by WOLFIE-OG** [comment]
pretty sure the none type would be username
from looking at the error

**Comment by BlackHacker511** [comment]
try it not it should work
on every system (Windows, Linux, macOS)
and yes the issue was the username
each system has different env code
the logic was wrong so I had to correct it

Enjoy
