### ISSUE TITLE
Visual Studio Version

### ISSUE THREAD

**Issue by ethanchua07** [BlackHacker511/BlackNET#71]
What version of visual studio do you use to edit the source i use 2019 version but it show error?

**Comment by BlackHacker511** [comment]
It was built on VS 2013

**Comment by ethanchua07** [comment]
will it work in 2015 version?

**Comment by BlackHacker511** [comment]
Yes it should all you need is at least .NET Framework 4.0 Installed on your computer and when you open it the source disable your anti-virus if you have one then compile it and it will work without issues

**Comment by ethanchua07** [comment]
it show error on 2015
![error](https://user-images.githubusercontent.com/62959377/78112340-ae50bb00-7430-11ea-9549-f9be31e7f224.png)

**Comment by BlackHacker511** [comment]
What's the error

Needs a screenshot and logs if you have

**Comment by BlackHacker511** [comment]
Close Form1.vb [ Design] then compile the source cod

**Comment by ethanchua07** [comment]
it works now thankyou,😊 the source of stub.exe is the PHPStub?

**Comment by ethanchua07** [comment]
i think theres a problem in client at 1st the command executed successful in 4th to 5th attempt nothing happen you need to end the process and restart to execute the command,

**Comment by ethanchua07** [comment]
i am using xampp 7.3

**Comment by BlackHacker511** [comment]
I am looking into this issue.
