### ISSUE TITLE
000webhosting error

### ISSUE THREAD

**Issue by sirdankmemes** [BlackHacker511/BlackNET#73]
after i press install it shows me this 

### 

> Problem in executing the SQL query CREATE TABLE `admin` ( `id` int(11) UNSIGNED NOT NULL, `username` text NOT NULL, `password` text NOT NULL, `email` text NOT NULL, `role` text NOT NULL, `s2fa` varchar(10) NOT NULL, `secret` varchar(100) NOT NULL, `sqenable` varchar(10) NOT NULL, `question` text NOT NULL, `answer` text NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

i checked the the database its empty still

**Comment by Odsku** [comment]
For me it worked you need To change some details and it works (change the login information to the database)

**Comment by Odsku** [comment]
I mean it works for me ( you need To remove 2fa i think since i removed it and it worked fine

**Comment by sirdankmemes** [comment]
> I mean it works for me ( you need To remove 2fa i think since i removed it and it worked fine

and how did u remove 2fa?

**Comment by Odsku** [comment]
Remove the 2factor from login.php

**Comment by Odsku** [comment]
Did u make a database to the website and sdded those login details to the database.php?

**Comment by MarkSkith4** [comment]
Same thing is happening with me, I'm hosting on a windows server vps

**Comment by Odsku** [comment]
> Same thing is happening with me, I'm hosting on a windows server vps


Did you setup an mysql database and changed the password and uswrname that the php is trying to login to if you need help i can probably help u

**Comment by BlackHacker511** [comment]
I am going to reference you to this issue #87 try the provided solution it might work for you.
