### ISSUE TITLE
Upload Request

### ISSUE THREAD

**Issue by ethanchua07** [BlackHacker511/BlackNET#76]
how to upload file in the webhosting from temp folder

cd /d %temp%
dir c:\ >dir.txt

the command will list dir in drive c and and write to file dir.txt in temp folder.
my problem is how can i upload it to webhosting server.
sorry for my problem..haha this is great tool for who have problem in port forwarding thx for this hope to have more feature in future.

**Comment by BlackHacker511** [comment]
I will try to create the function no promises but it is a nice function to add and i'm thinking i might create a simple file manager to just view and upload files from a specific location.

**Comment by ethanchua07** [comment]
thank you,😊 1 thing when you clear temp in command, the script you executed .bat .ps1 is not deleted,
