### ISSUE TITLE
Website dies

### ISSUE THREAD

**Issue by peckingduck101** [BlackHacker511/BlackNET#78]
the website works all fine for quite some time, until i start executing stuff on people, the website tells me to go to install.php again. that does not work, ive hosted around 5 000webhost sites now and that keeps happening, i can execute things but usually on their end the exe closes and it just ruins it from working, and also you should explain where the password grabbing goes.

**Comment by BlackHacker511** [comment]
1. Don't Use 000webhost
2. When the page tells to go to install.php that you exceeded your mysql limit another 000webhost problem
4. You will get banned from using BlackNET on 000webhost
3. I have explained it hundreds of times in the upload folder

This issue is invalid
