### ISSUE TITLE
Client's do not go offline...

### ISSUE THREAD

**Issue by KUSHHACKING** [BlackHacker511/BlackNET#79]
Hello, dear BlackHacker511,
I downloaded your BlackNET Remote Admin Tool and it working fine, but I can't grab there DATA and they seem to be online, although they offline...
Can you help me?

**Comment by BlackHacker511** [comment]
You need to enable the ping system.
Just Follow this tutorial.
https://www.youtube.com/watch?v=rHCYGRA1h54

**Comment by KUSHHACKING** [comment]
Hello BlackHacker511,
Thank you now I see if they online or not, but I start keylogger and nothing happens and it doesn't takes screenshots... You're sure it works?

**Comment by KUSHHACKING** [comment]
And next Error "Please Go To install.php"
nothing work any more bro ;C

**Comment by BlackHacker511** [comment]
@KUSHHACKING if you are on 000webhost just give 24 hours because that's mean you exceeded your mysql limit

**Comment by BlackHacker511** [comment]
@KUSHHACKING for now try to give the uploads folder 777 and every folder inside it and i am looking into this issue.
