### ISSUE TITLE
more python errors :)

### ISSUE THREAD

**Issue by WOLFIE-OG** [BlackHacker511/BlackNET#8]
Python 3.7.4 (default, Jul  9 2019, 00:06:43)
[GCC 6.3.0 20170516] on linux
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    basecode = base64.urlsafe_b64encode(username.encode('UTF-8')).decode('ascii')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by BlackHacker511** [comment]
there are no issues it works perfectly on Linux and Windows Python 3 and 2 
I tried it and the python code works with no issues

![](https://i.imgur.com/XpdAawZ.png)
