### ISSUE TITLE
Web Panel Feature Request

### ISSUE THREAD

**Issue by ethanchua07** [BlackHacker511/BlackNET#80]
hello i wonder if you could add sort in tables like this
https://startbootstrap.com/previews/sb-admin/

and ability to select multiple client using ctrl+click like when you hover in table it will highlight whole row, and an option to remove offline client would be usefull too. im sorry im not good in coding..thank you and godbless.:)

**Comment by BlackHacker511** [comment]
Great ideas to add i will see what i can do with them

**Comment by ethanchua07** [comment]
how can i adjust the table row height it seems that it eats so much space i tried to find it using inspect element but i cant find it,
