### ISSUE TITLE
bot offline online 

### ISSUE THREAD

**Issue by jermalin** [BlackHacker511/BlackNET#82]
hi, i tested you panel and builder panel have problem not working offline online bot, also for me binder not working win10 and please tell me what time you think make new realise ?

**Comment by BlackHacker511** [comment]
For Online/Offline Enable ping System

Follow this Tutorial
https://www.youtube.com/watch?v=rHCYGRA1h54

And I'm not going to rush the new version v3.0 was rushed to production and it was bad

and might take 3 to 4 months
