### ISSUE TITLE
PHP Errors everywhere

### ISSUE THREAD

**Issue by LeonidasHD143** [BlackHacker511/BlackNET#83]
**Describe the bug**
Issues across the entire setup, there are php errors everywhere and i cant get them cleared

**To Reproduce**
1. Follow the YT Tutorial
2. work

**Expected behavior**
The site and panel should work, but it doesn't

![image](https://user-images.githubusercontent.com/38572203/79765238-594bea80-82f4-11ea-8f04-fa4b39d7ceae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Comment by BlackHacker511** [comment]
What is the Webhosting you are using?

Because from the errors, the are no files in vendor folder

try to give everything in BlackNET Folder 777 permission.

**Comment by LeonidasHD143** [comment]
000webhost

**Comment by LeonidasHD143** [comment]
oh there are no files in the vendor, where would i find these?

**Comment by LeonidasHD143** [comment]
nevermind i found them
