### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by 0niel** [BlackHacker511/BlackNET#84]
Does not work on Windows 10. Absolutely. Does not create a single bot if the program was run on win 10. I also noticed that none of the requests from the control panel are executed by the bot.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version latest

**Comment by 0niel** [comment]
Fixed. The problem was that $_GET ['data'] dropped the " + " character from the URL, so the value was decoded incorrectly and sanitize dropped it as if it was in the wrong encoding. 
The problem was solved by adding str_replace

**Comment by BlackHacker511** [comment]
> Fixed. The problem was that $_GET ['data'] dropped the " + " character from the URL, so the value was decoded incorrectly and sanitize dropped it as if it was in the wrong encoding.
> The problem was solved by adding str_replace

Copy the new code and add here in a code block

```
Code Here
```

So I can add the solution to the new version.

**Comment by BlackHacker511** [comment]
Done I added the fix to local code.
