### ISSUE TITLE
feature take screen and many feature not work.

### ISSUE THREAD

**Issue by M0sterHxck** [BlackHacker511/BlackNET#85]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlackHacker511** [comment]
Make Sure that Upload Folder with everything inside it and upload.php has 777 permission.

This will help you fix

1. Screenshot
2. Firefox Cookies
3. Chrome Cookies
4. Bitcoin Wallet
5. Password Stealer*



*password stealer might not work on your client until the new fix.
