### ISSUE TITLE
install.php SQL error

### ISSUE THREAD

**Issue by BetaIRL** [BlackHacker511/BlackNET#87]
when i click on start instalation:

Problem in executing the SQL query CREATE TABLE `admin` ( `id` int(11) UNSIGNED NOT NULL, `username` text NOT NULL, `password` text NOT NULL, `email` text NOT NULL, `role` text NOT NULL, `s2fa` varchar(10) NOT NULL, `secret` varchar(100) NOT NULL, `sqenable` varchar(10) NOT NULL, `question` text NOT NULL, `answer` text NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by richihartawan** [comment]
Check config.php

<?php

$host ="...";
$username ="...";
$password ="...";
$database ="...";
$connect =mysqli_connect ($host,$username,$password,$database);

?>

**Comment by BetaIRL** [comment]
> Check config.php

where ? i dont see it

**Comment by richihartawan** [comment]
What app are you using to make database? If you using xampp, check the name database, if that similar name in database cannot install in php

**Comment by BlackHacker511** [comment]
1. Are you using XAMPP ?
2. did update classes/Database.php ?

**Comment by BetaIRL** [comment]
Oh thank you it was because i named booth the same :/ now it works :D

**Comment by richihartawan** [comment]
@BetaIRL haha okeyy youre welcome
