### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by spicyhustle** [BlackHacker511/BlackNET#88]
![image](https://user-images.githubusercontent.com/64509943/80553776-51aed480-89cb-11ea-816b-b01f8a1968b2.png)

Installing brings up this error:

Problem in executing the SQL query CREATE TABLE `admin` ( `id` int(11) UNSIGNED NOT NULL, `username` text NOT NULL, `password` text NOT NULL, `email` text NOT NULL, `role` text NOT NULL, `s2fa` varchar(10) NOT NULL, `secret` varchar(100) NOT NULL, `sqenable` varchar(10) NOT NULL, `question` text NOT NULL, `answer` text NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

Checked in 4 different hosts help pls.

**Comment by BlackHacker511** [comment]
Check this issue he had the same problem it might work for you

#87

**Comment by aloisberngardt** [comment]
I have this problem too But it's not really error. If table admin already exists, it shows this error.

**Comment by BlackHacker511** [comment]
It's not an issue if any table exists in the database with the same name the installer can't write over it
