### ISSUE TITLE
Public IP or Private IP?

### ISSUE THREAD

**Issue by Deb-kal** [BlackHacker511/BlackNET#9]
Hi,
I’m not very friendly with bots connexion but my question is : If I want someone who is not connected to my network to connect to BlackNET which IP should I use ? 
I mean, if I build the client with the url 192.168.x.x/blacknet/  can bots connect to it?

**Comment by BlackHacker511** [comment]
depends if you want to run it locally you need to use either of 127.0.0.1 or your local IP aka Private IP
and if you want to use it globally

1. open port 80 in your router
2. install the panel
3. in the builder use the public IP or you DNS URL aka No-IP

Good Luck

**Comment by Deb-kal** [comment]
Thanks I’m gonna try it out !
Is BlackNET using encryption to make the connexion secure ?

**Comment by BlackHacker511** [comment]
No, but I will try to add encryption in the new version
