### ISSUE TITLE
install.php not working

### ISSUE THREAD

**Issue by iii235** [BlackHacker511/BlackNET#90]
I did exactly what the tutorial did. I put in the url "scrawled-cones.000webhostapp.com/blacknet/install.php" but it give me a page not found error.

**Comment by BlackHacker511** [comment]
Hello,

Make sure that the name of the folder is correct because 404 means you don't have files inside blacknet or blacknet folder does not exist.

**Comment by iii235** [comment]
My website does have all the files pasted in. install.php is spelled correctly.

**Comment by iii235** [comment]
Nevermind, I solved the issue. I just had to move the blacknet folder into the html folder.

**Comment by byadgamer** [comment]
Hi sir.....the program is working fine. But what is BN url and the default one - localhost/blacknet shows that my panel is not working or disabled. Please help me. Thank you in advance and hope you keep bringing us projects like these.

**Comment by BetaIRL** [comment]
Rename BlackNET Panel to Panel for example than copy it into your html folder and than open the URL: Adress/Panel/install.php thats how simple it is :)
