### ISSUE TITLE
Panel not working pls help 

### ISSUE THREAD

**Issue by byadgamer** [BlackHacker511/BlackNET#91]
**Describe the bug**
The default BN url shows that the panel is invalid or not working

Hi sir.....the program is working fine. But what is BN url and the default one - localhost/blacknet shows that my panel is not working or disabled. Please help me. Thank you in advance and hope you keep bringing us projects like these.

**Comment by BlackHacker511** [comment]
Could you show me how did you write it a screenshot from the builder with domain written in the builder.

And a screenshot from blacknet folder
