### ISSUE TITLE
not working plssss help fast

### ISSUE THREAD

**Issue by byadgamer** [BlackHacker511/BlackNET#93]
I tried to use the botnet on my own device.But none of the commands are working

**

 Sir, im sorry to disturb you, but i tried to use this on my on pc. When i opened the compiled program, the bot was showing up in my panel. But none of the commands are working. No script execution, etc. When i took a screenshot, it showed taken in the logs but nothing happened. When i ended all processes, the botnet still shows up, saying it is active. I'm not getting what mistake I'm making. A help would me much appreciated. Thank you in advance sir.

**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [HP PC]
 - OS: [WIN10]
 - Browser [Chrome]

Hope you reply to me soon.

**Comment by BlackHacker511** [comment]
1. Make Sure that the upload folder has 777 permission
2. Enable ping.php using cronjob
3. Make sure that your AV does not block the connection
4. I would appreciate that you open one issue and just update it with your problem

**Comment by byadgamer** [comment]
sir, here is the screenshot of my blacknet folder in the file manager, the interface, and the logs.
i couldnt understand what did you mean by  THE BUILDER and i cant find any ping.php. 
![Capture  2 2](https://user-images.githubusercontent.com/64799362/80999119-c8335280-8e61-11ea-8875-ae6bfc5602de.JPG)
Thank you in advance
![Capture 2 3](https://user-images.githubusercontent.com/64799362/80999123-c9647f80-8e61-11ea-9dfd-c0e4bbb4c137.JPG)
![Capture 3](https://user-images.githubusercontent.com/64799362/80999126-c9fd1600-8e61-11ea-9d4e-0f3a6809769f.JPG)
![Capture1](https://user-images.githubusercontent.com/64799362/80999128-ca95ac80-8e61-11ea-9af5-27be364d3e63.JPG)
![Capture2 1](https://user-images.githubusercontent.com/64799362/80999133-cb2e4300-8e61-11ea-9934-00e642c8f89c.JPG)

**Comment by byadgamer** [comment]
i have enabled ping.php with cronjob for every 10 minute. is it fine sir?

![Capture12](https://user-images.githubusercontent.com/64799362/80999725-c4ec9680-8e62-11ea-8f14-f401aaf0ff5e.JPG)

**Comment by byadgamer** [comment]
please help me sir.

**Comment by BlackHacker511** [comment]
1. Make sure that the bot is running and didn't close it self

2. Did you give everything inside upload folder 777 permissions

3. Use cron-job.org it's better than the 000webhost cronjob system

4. I am working on an overall fix the command issue it will implemented next release and I hope it will work.

**Comment by byadgamer** [comment]
it worked. Thank you.
Just wanted to point out that few of the functions such as execute script doesnt work and the password stealer crashes the bot. Hope this would be fixed and the next release will be out soon.

**Comment by BlackHacker511** [comment]
> it worked. Thank you.
> Just wanted to point out that few of the functions such as execute script doesnt work and the password stealer crashes the bot. Hope this would be fixed and the next release will be out soon.

Great

1. I am working on a fix for execute script function
2. Password Stealer Does not work after the new chrome update I am working on a fix for that too.

Enjoy
