### ISSUE TITLE
Stub Not Found

### ISSUE THREAD

**Issue by iii235** [BlackHacker511/BlackNET#94]
The client builder is telling me that it can't find a stub, even though I have the latest version of the Net Framework.

**Comment by iii235** [comment]
So I found the stub, and I tried to put in in the Blacknet directory, but it gets deleted. Windows Defender and my Antivirus are both off, but the stub.exe gets deleted without any warning.

**Comment by BlackHacker511** [comment]
Make sure you don't have hidden malwares with botkiller on your machine and make sure that any and every AV is off

**Comment by iii235** [comment]
All of my AV's are off. I think it might be a problem with File Explorer. Whenever I download the stub, it sticks around in File Explorer's Downloads for a few seconds before disappearing. I don't get any notification from AV, so Defender or my personal AV can't be the problem. I haven't downloaded anything sketchy recently, so it can't be a botkiller.

**Comment by HritikR** [comment]
@iii235  Turn off Windows Defender!!!

**Comment by iii235** [comment]
It is off, and my other anti virus.

**Comment by BlackHacker511** [comment]
> It is off, and my other anti virus.

Make sure that stub.exe is not in Windows Defender Quarantine List

**Comment by iii235** [comment]
I checked both lists, stub isn't in the quarantine list

**Comment by iii235** [comment]
Can you just encypt the stub.exe file?

**Comment by iii235** [comment]
I will email you a video on what happens when I try to download the stub. All AVs are off.

**Comment by BlackHacker511** [comment]
@iii235 

Aha that's why the stub gets deleted!. 

Don't use Chrome because it has a built-in Antivirus. 

Use something like Firefox or download the whole repository as Zip file then extract it.

**Comment by iii235** [comment]
Mozzila didn't work. It says that it can't find the file, and when I go to
Downloads in File Explorer, nothing is there. Trust me, ALL my Antivirus
and Windows Defender are off.

**Comment by BlackHacker511** [comment]
@iii235 i will give an alternative link to download the project from and tell what happens just let me upload it.

**Comment by BlackHacker511** [comment]
> Mozzila didn't work. It says that it can't find the file, and when I go to Downloads in File Explorer, nothing is there. Trust me, ALL my Antivirus and Windows Defender are off.

@iii235 this is a new link https://shortty.co/ocBnj try and download it from there and tell me if it works.

**Comment by iii235** [comment]
Sorry, no luck. Jesus, why are all these Browsers so paranoid about stub.exe files? I tried to download other rats that need stubs, but Google Chrome also removed the files.

**Comment by iii235** [comment]
Welp, I just decided to run the client builder from Kali Linux. Thankfully, the stub doesn't get deleting in Linux systems.
