### ISSUE TITLE
Issue ?

### ISSUE THREAD

**Issue by byadgamer** [BlackHacker511/BlackNET#95]
Hope you'll help me and bring the next update soon as some features smarent working in this one..... Thank you. 

ANY WAY TO CREATE THE BACKDOOR/CLIENT UNDETECTABLE BY THE AV BECAUSE WHEN I SENT IT TO MY FRIENDS THEIR AV IS DELETING IT. Any help would be appreciated.

**Comment by BlackHacker511** [comment]
Yes

1. Open BlackNET Builder.exe
2. Enter your blacknet url
3. Choose the features from checkboxs
4. Click. Compile and save the backdoor


Enjoy

**Comment by byadgamer** [comment]
**

**> 1. I think you didnt get me sir.
> I want to compile the backdoor such that my antivirus doesnt detect it. But it is detecting each and every time. I have attached a screenshot of the file below.**

**
2. And there is an update button which says to download the update but i think its already the latest version. Just clarify whether it is a bug or not.

Thank you.
![save](https://user-images.githubusercontent.com/64799362/81286941-8849b680-907f-11ea-90f3-38036f2d3864.JPG)

**Comment by BlackHacker511** [comment]
Ahaa

Juar disable your Antivirus then compile the backdoor you need obfuscate the output

This video will give you an idea how to obfuscate it

https://youtu.be/hzC8_UYGor0

And yes the update function has a bug and it will be fixed in the next the release.

**Comment by byadgamer** [comment]
sir, Thank you for your above response. I found it very helpful. But when I'm trying to compile the program in the Obsfucator there is this error/warning showing up. I jreally cant understand what that is. In addition to that, some program even stops while its obsfucating. The images for reference are attached below. 
Thank you.
![Capture](https://user-images.githubusercontent.com/64799362/81401043-14c1ab00-914c-11ea-942b-6aafd4b29381.JPG)
![1](https://user-images.githubusercontent.com/64799362/81401046-14c1ab00-914c-11ea-8d8d-fbf4f421da55.JPG)
![2](https://user-images.githubusercontent.com/64799362/81401040-12f7e780-914c-11ea-9857-4b17ef86e4a9.JPG)

**Comment by BlackHacker511** [comment]
@byadgamer 

This warnings just to tell you the function SteelPassword might interfere with obfuscation 

Does the output works?
If yes then go ahead and you use it

Enjoy

**Comment by byadgamer** [comment]
The output works sir and I hope the password stealer will be fixed along with a few other things in the next release.
But While I was testing the backdoor today, I got an error which i didn't get before. When i try to steal chrome cookies, this error comes up. I have attached the image of the error below.
Thank you.
![3](https://user-images.githubusercontent.com/64799362/81404949-4fc7dc80-9154-11ea-94a3-d77150dfb534.JPG)

**Comment by BlackHacker511** [comment]
Thank you for reporting the issue and I will fix in the next release

**Comment by byadgamer** [comment]
I just had a few more questions sir -
1. What is Enable Watchdog? 
2. What does stealth mode do?
3. how does USB spread work?  ( It just transfers the backdoor into another USB. Does it autorun     
                                                       when the usb is plugged in some other computer? )

Thank you.

**Comment by BlackHacker511** [comment]
1. The Watchdoh is a service that's run with the backdoor to make sure that the client does not close it when the client closes your backdoor the watchdog will try to rerun it

2. Stealth mode will melt you backdoor in the client machine and hide it from his eyes

3. The USB Spreed will scan the any USB drive then create a shortcut of all the files and folders inside that drive* and infect the shortcuts with a malicious code. 

* Sometimes it works and othera it just copy some files and infect them

**Comment by byadgamer** [comment]
So if I compile the backdoor with USB spread on, it will infect the files? Because I just saw that it copies the backdoor there.
And is there any way to autorun the backdoor when the infected USB is plugged in some other computer?
Thank you sir.

**Comment by BlackHacker511** [comment]
@byadgamer

 this is what suppose to happen it doesn't always work sometimes it do it on have the files 

1. Copy the backdoor to USB

2. Hide the Backdoor

3. Scan the USB for files and folders

4. Create shortcuts inside the USB of thd fildes and folders 

5. Hide the original files 

6. Infect the shortcut with a malicious code that runs your backdoor every time a user click on a should

**Comment by byadgamer** [comment]
Thanks a lot sir.
