### ISSUE TITLE
suggestion;question

### ISSUE THREAD

**Issue by byadgamer** [BlackHacker511/BlackNET#96]
Sir, I would like to recommend a few features to be added in the next release and also had a question.

1. Is there any way to add an external plugin into the blacknet commands ? (for example - the plugins in https://github.com/malwaredllc/byob/tree/master/byob/modules ). If so how?

2. Please add these in the next release if possible - Fix the passwprd stealer, add a webcam support, fix the same screenshot upload bug, fix the script execution bug, and also a bitcoin miner if possible. 

Thank you.

**Comment by BlackHacker511** [comment]
1. You can I will try to add in the next release it will be custom DLl system you create your own plugin then execute it on the client machine

2.
Password plugin ( Done )
Screenshot Fix ( Done )
Script execute fix ( Done )
Bitcoin Miner you can upload and execute your own there is a lot of open source miners just edit it amd upload it to the client machine
Webcam support I might add something like the screenshot Just capture an image of the camera and uploaded but I don't promise that but I will see what I can do

**Comment by byadgamer** [comment]
And when would the next release be?
I'm eagerly waiting for it.

**Comment by BlackHacker511** [comment]
@byadgamer A month or two I am not going to rush I am collecting a lot of issues and fixing them adding more features so I can make as complete as I can.
