### ISSUE TITLE
Cannot send commands after sending first command when installed on client

### ISSUE THREAD

**Issue by karilvo** [BlackHacker511/BlackNET#97]
I ran the executable file and installed on PC. After running first command, I am no longer able to execute any commands, but it still shows the client available in the panel. Also, the executable is still running on the PC. 

Any suggestions on fixing? Only solution is running the executable so far, but was hoping this isn't needed every a command is launched.

(Windows 10 PC)

**Comment by BlackHacker511** [comment]
What is the first command that you execute it.

**Comment by BlackHacker511** [comment]
@Jhin7F dont worry about it

I need a screenshot from the log page

Because I don't see the issue on my end either I fixed already or there isn't one.

If I fixed already it will be in the next release

**Comment by karilvo** [comment]
Can't login panel at the moment. It's telling me to go to login.php. Received maximum queries error when I tried checking db as well

**Comment by karilvo** [comment]
Screenshot for log page: https://gyazo.com/c1d50cfcf1b23739fe65bb5c38c0a6a6

**Comment by BlackHacker511** [comment]
@karilvo that's a 000webhost issue they have an SQL Limit but what's the DDOS Attack that you ran because I don't see it in the log.

**Comment by karilvo** [comment]
Logs after: https://gyazo.com/dedcf7e67fe6fdb7831e204258e92906

It's strange. Sometimes a command will go through but sometimes it won't. Quick question, if I'm trying to attack target and I have ip/port. It's okay if I do x.x.x.x:####? (x being ip & # being port). Server I was testing on wasn't being affected by neither udp or bandwidth attack using BlackNet ddos options, but I could nearly take it down with a normal UDP flooding tool. Know any reasons it's not affecting game server?

**Comment by BlackHacker511** [comment]
Ok I see trying to do

1. Wait at least 1 minutes between commands

2. It's a botnet you need bots to attack a server

3. For know it just attack port 80 i might add a way to make the port custom in the next release

**Comment by karilvo** [comment]
Ok, many thanks. Last question I have is any recommended hosts? I only tried with 000webhosting and my computer. Got some rest and woke up, but the 000webhosting site has been suspended unfortunately. Apart from that, UDP attack would be able to attack a game server and affect it regardless of the specific port it uses?

**Comment by BlackHacker511** [comment]
@karilvo you will be able to attack a game server and affect it but you need clients/bots so you can use them to make the attack
