### ISSUE TITLE
"Please Remove install.php or update.php if they exist"

### ISSUE THREAD

**Issue by angeloch** [BlackHacker511/BlackNET#98]
"Please Remove install.php or update.php if they exist"
You are unable to install, this warning appears ... What should I do now?

**Comment by BlackHacker511** [comment]
Remove install.php or update.php from BlackNET folder if they exist

**Comment by angeloch** [comment]
it worked! the only problem after executing the command nothing happens to the client.

**Comment by BlackHacker511** [comment]
> it worked! the only problem after executing the command nothing happens to the client.

What is the command are you executing

Overall Fix
Give the upload folder 0777 permissions
Make sure the client did not close it self
Password Stealer Does not work and might crash the client

**Comment by angeloch** [comment]
it was a message command test. Could you help me how to make such permission for the command to start working?

**Comment by angeloch** [comment]
I'm confused, I'm from Brazil, I'm trying a little to understand English well, even with a translator. Sorry

**Comment by BlackHacker511** [comment]
> it was a message command test. Could you help me how to make such permission for the command to start working?

What hosting are you using?

**Comment by angeloch** [comment]
000webhost

**Comment by BlackHacker511** [comment]
> 000webhost

Watch this video to set up the panel on 000webhost step by step

[https://www.youtube.com/watch?v=ReKOuh6fFcQ&t=192s](https://www.youtube.com/watch?v=ReKOuh6fFcQ&t=192s)

**Comment by angeloch** [comment]
I did it, friend. Thank you. Congratulations on the work. Are all the commands working? I haven't tested them all yet!

**Comment by BlackHacker511** [comment]
@angeloch

DDOS Commands have issues it will be fixed in the next release

Password Stealer doesn't work because of the Chrome update it will fixed in the next release.

And the other all works just wait at least 1 minutes between commands.

**Comment by angeloch** [comment]
Great, one last doubt, I promise; When I run the screen capture command, where can I see these captures? Where are the data generated being stored?
