### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by byadgamer** [BlackHacker511/BlackNET#99]
Sir, I tried to access my database today after several days of it being offline, but no-ip and 000webhost, both say that theyve terminated my account because i voilsted their terms of services.

When i tried to create a new one, this message is coming. PLease help me fix it.
Thank you.
![Capture](https://user-images.githubusercontent.com/64799362/81907244-12949c00-95e5-11ea-9923-e981daaad35d.JPG)

**Comment by byadgamer** [comment]
okay so that got fixed on its own but now this is coming. Plssss help me out sir
![Capture](https://user-images.githubusercontent.com/64799362/81926711-00742700-9600-11ea-84a5-381a7489ca10.JPG)

**Comment by BlackHacker511** [comment]
Just show me the database and the Database.php file

Take a screenshot of both of them

**Comment by byadgamer** [comment]
![1](https://user-images.githubusercontent.com/64799362/81934407-8a29f180-960c-11ea-89bd-7d900fda747b.JPG)
![2](https://user-images.githubusercontent.com/64799362/81934410-8b5b1e80-960c-11ea-9903-7894f52b5fbc.JPG)
![3](https://user-images.githubusercontent.com/64799362/81934413-8c8c4b80-960c-11ea-8289-171eaaf8c317.JPG)
you meant this by the database screenshot right?

**Comment by BlackHacker511** [comment]
> ![1](https://user-images.githubusercontent.com/64799362/81934407-8a29f180-960c-11ea-89bd-7d900fda747b.JPG)
> ![2](https://user-images.githubusercontent.com/64799362/81934410-8b5b1e80-960c-11ea-9903-7894f52b5fbc.JPG)
> ![3](https://user-images.githubusercontent.com/64799362/81934413-8c8c4b80-960c-11ea-8289-171eaaf8c317.JPG)
> you meant this by the database screenshot right?

Screenshot of the admin table

**Comment by byadgamer** [comment]
i am not bieng able to access my phpadmin database so i made a new one.....but i cannot access that too and this is coming when I open my website with the new database 

Parse error: syntax error, unexpected 'localhost' (T_STRING), expecting ',' or ';' in /storage/ssd4/765/13695765/public_html/classes/Database.php on line 6

what shall i do now sir?

**Comment by BlackHacker511** [comment]
@byadgamer contact me on my Telegram [@BlackHacker511](https://t.me/BlackHacker511) so I can assist you. or send me an email with your 000webhost information on farisksa79@protonmail.com
